///////////////////////////////////////////////////////////
//  ExamesDoAtendimento.cs
//  Implementation of the Class ExamesDoAtendimento
//  Generated by Enterprise Architect
//  Created on:      13-jun-2016 20:25:24
//  Original author: Maico
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Windows.Forms;
using PlanoDeSaude.DAO;

namespace PlanoDeSaude.Model
{

    public class ExamesDoAtendimento
    {
        private DateTime dataExame;
        private int id;
        private string status;
        private Exame _objExame;
        private Atendimento _objAtendimento;

        public ExamesDoAtendimento(Atendimento atendimento)
        {
            _objAtendimento = atendimento;
        }
        public DateTime DataExame
        {
            get { return dataExame; }
            set { dataExame = value; }
        }
        public int Id
        {
            get { return id; }
            set { id = value; }
        }
        public string Status
        {
            get { return status; }
            set { status = value; }
        }
        public Atendimento ObjAtendimento
        {
            get { return _objAtendimento; }
            set { _objAtendimento = value; }
        }
        public Exame ObjExame
        {
            get { return _objExame; }
            set { _objExame = value; }
        }

        public void Save()
        {
            new ExamesDoAtendimentoDAO().Inserir(this);
        }
        public void Remove()
        {
            new ExamesDoAtendimentoDAO().Deletar(this);
        }
    } //end ExamesDoAtendimento
}